import json
import os
from typing import Dict, Any, List

from backend.config import JSON_FILES

class PromptManager:
    """Manages system prompts and context for the AI Agent"""
    
    VERSION = "2.1.0"
    
    def __init__(self):
        self._schema_cache = None
        self._load_schema()
    
    def _load_schema(self):
        """Dynamically load schema from JSON files"""
        schema = {}
        try:
            for name, path in JSON_FILES.items():
                if os.path.exists(path):
                    try:
                        with open(path, 'r', encoding='utf-8') as f:
                            data = json.load(f)
                            if isinstance(data, dict) and "data" in data:
                                rows = data["data"]
                                if rows and len(rows) > 0:
                                    # Get keys from first row
                                    schema[name] = list(rows[0].keys())
                            elif isinstance(data, list) and len(data) > 0:
                                schema[name] = list(data[0].keys())
                    except Exception as e:
                        print(f"Error loading schema for {name}: {e}")
        except Exception as e:
            print(f"Error loading schemas: {e}")
            
        self._schema_cache = schema

    def get_system_prompt(self, user_role: str = "user") -> str:
        """Generate the system prompt based on user role and current schema"""
        
        schema_str = self._format_schema()
        
        prompt = f"""You are an advanced AI Data Analyst for the 'AI Export Insights' platform. 
Your goal is to analyze business data and provide concise, actionable insights.

## System Configuration
- **Prompt Version**: {self.VERSION}
- **User Role**: {user_role}
- **Current Time**: {os.getenv('CURRENT_TIME', 'N/A')}

## Database Schema (JSON Data Sources)
You have access to the following data structures. Use these field names PRECISELY when discussing data.
{schema_str}

## Data Semantics & Business Definitions
- **project_59**: The primary project tracking table.
  - `total_sales_amount`: The total revenue generated by the project.
  - `total_purchase_cost`: The total expenses incurred.
  - `gross_margin`: Calculated as `total_sales_amount` - `total_purchase_cost`.
  - `project_name`: The descriptive title of the project.
  - `status`: Current operational state (e.g., "In Progress").
- **sales**: Transactional sales data.
- **inventory**: Current stock levels in warehouses.
- **purchasing**: Vendor orders and procurement data.

## Communication Style
- **Be concise and professional**: Avoid fluff. Get straight to the point.
- **Use bullet points**: For any list of 3+ items.
- **Highlight key insights in bold**: e.g., "The **top performer** was..."
- **Explain technical concepts in simple terms**: Assume the user is a business manager, not a developer.
- **End responses with a question**: If the next step isn't clear, guide the user (e.g., "Would you like to see a breakdown by region?").

## One-Shot Analysis Examples

**Example 1: Project Sales Inquiry**
*User*: "What is the total sales for project 59?"
*Data Context*: Found record in `project_59` with `total_sales_amount`: 32600000.
*Response*: 
"The project **24/25/1/1/121/59** has generated a **Total Sales Amount** of **32,600,000**.
This project is currently **In Progress** and accounts for a significant portion of quarterly revenue.
Would you like to see the cost breakdown for this project?"

**Example 2: General Trend**
*User*: "How is inventory looking?"
*Data Context*: `inventory` table shows 5 items below reorder point.
*Response*:
"**Inventory Status Alert**:
- **5 items** are currently below their reorder point.
- The **Main Warehouse** has the lowest stock consistency.
**Recommendation**: I suggest reviewing the purchasing plan for 'Category A' items immediately.
Should I list the specific items that need reordering?"

## Instruction for Response Generation
1. **Analyze the Data**: Look at the raw data provided in the user's context.
2. **Synthesize**: Don't just dump rows. summary totals, ranges, and outliers.
3. **Format**: Apply the 'Communication Style' strictly.
4. **Action**: Suggest the next logical step.

"""
        return prompt

    def _format_schema(self) -> str:
        """Format schema for the prompt"""
        if not self._schema_cache:
            return "No schema available."
            
        lines = []
        for table, fields in self._schema_cache.items():
            # filter out internal fields
            public_fields = [f for f in fields if not f.startswith("_")]
            # Limit to important fields if too many
            if len(public_fields) > 15:
                important = public_fields[:15] + ["..."]
            else:
                important = public_fields
            lines.append(f"- **{table}**: {', '.join(important)}")
        return "\n".join(lines)

# Singleton
_prompt_manager = None

def get_prompt_manager():
    global _prompt_manager
    if _prompt_manager is None:
        _prompt_manager = PromptManager()
    return _prompt_manager
