import re
import os

def convert_sql(input_file, output_file):
    print(f"Reading {input_file}...")
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    print("Converting SQL syntax...")
    
    # 1. Helper function to remove specific blocks
    def remove_pattern_lines(text, pattern):
        return re.sub(pattern, '', text, flags=re.MULTILINE | re.IGNORECASE)

    # 2. Basic Cleanup
    # Remove clutter
    content = re.sub(r'USE\s+.*', '', content, flags=re.IGNORECASE)
    content = re.sub(r'ALTER\s+DATABASE\s+.*', '', content, flags=re.IGNORECASE)
    content = re.sub(r'SET ANSI_NULLS (ON|OFF)', '', content, flags=re.IGNORECASE)
    content = re.sub(r'SET ANSI_PADDING (ON|OFF)', '', content, flags=re.IGNORECASE)
    content = re.sub(r'SET QUOTED_IDENTIFIER (ON|OFF)', '', content, flags=re.IGNORECASE)
    
    # Remove IDENTITY_INSERT commands
    content = re.sub(r'SET IDENTITY_INSERT\s+.*?\s+(ON|OFF)', '', content, flags=re.IGNORECASE)
    
    # 3. Data Type Conversions (Handling [Type] format)
    # Important: Do strictly typed replacements first
    subs = [
        (r'\[nvarchar\]', 'VARCHAR'),
        (r'\[varchar\]', 'VARCHAR'),
        (r'\[datetime2\]', 'TIMESTAMP'),
        (r'\[datetime\]', 'TIMESTAMP'),
        (r'\[date\]', 'DATE'),
        (r'\[bit\]', 'SMALLINT'),  # Use SMALLINT for boolean 0/1 compatibility during import
        (r'\[uniqueidentifier\]', 'UUID'),
        (r'\[varbinary\]', 'BYTEA'),
        (r'\[image\]', 'BYTEA'),
        (r'\[text\]', 'TEXT'),
        (r'\[ntext\]', 'TEXT'),
        (r'\[smallint\]', 'SMALLINT'),
        (r'\[tinyint\]', 'SMALLINT'),
        (r'\[int\]', 'INTEGER'),
        (r'\[bigint\]', 'BIGINT'),
        (r'\[decimal\]', 'DECIMAL'),
        (r'\[float\]', 'DOUBLE PRECISION'),
        (r'\[money\]', 'DECIMAL(19,4)'),
        (r'\[real\]', 'REAL'),
        (r'\[numeric\]', 'NUMERIC'),
    ]
    
    for pattern, replacement in subs:
        content = re.sub(pattern, replacement, content, flags=re.IGNORECASE)

    # Replace types in CAST
    content = re.sub(r'AS\s+DateTime2', 'AS TIMESTAMP', content, flags=re.IGNORECASE)
    content = re.sub(r'AS\s+DateTime', 'AS TIMESTAMP', content, flags=re.IGNORECASE)
    content = re.sub(r'AS\s+Date\b', 'AS DATE', content, flags=re.IGNORECASE)

    # 4. Handle Max lengths
    content = re.sub(r'VARCHAR\(\s*max\s*\)', 'TEXT', content, flags=re.IGNORECASE)
    content = re.sub(r'VARBINARY\(\s*max\s*\)', 'BYTEA', content, flags=re.IGNORECASE)
    # Also handle BYTEA(max) if replacement happened earlier
    content = re.sub(r'BYTEA\(\s*max\s*\)', 'BYTEA', content, flags=re.IGNORECASE)
    
    # 5. Schema and Identifier cleanup
    content = content.replace('[dbo].', 'public.')
    # Replace remaining brackets with double quotes
    content = re.sub(r'\[([^\]]+)\]', r'"\1"', content)

    # 6. Column Definitions & Constraints
    content = re.sub(r'IDENTITY\(\s*1\s*,\s*1\s*\)', 'GENERATED BY DEFAULT AS IDENTITY', content, flags=re.IGNORECASE)
    content = re.sub(r'PRIMARY KEY CLUSTERED', 'PRIMARY KEY', content, flags=re.IGNORECASE)
    content = re.sub(r'PRIMARY KEY NONCLUSTERED', 'PRIMARY KEY', content, flags=re.IGNORECASE)

    # Remove WITH CHECK from ADD CONSTRAINT
    content = re.sub(r'WITH\s+CHECK\s+ADD', 'ADD', content, flags=re.IGNORECASE)
    
    # Remove ALTER TABLE ... CHECK CONSTRAINT ...
    content = re.sub(r'ALTER\s+TABLE\s+.*?\s+CHECK\s+CONSTRAINT\s+.*?(;|$)', '', content, flags=re.IGNORECASE | re.MULTILINE)
    
    # Remove CLUSTERED/NONCLUSTERED from CREATE INDEX
    content = re.sub(r'CREATE\s+(UNIQUE\s+)?(CLUSTERED|NONCLUSTERED)\s+INDEX', r'CREATE \1INDEX', content, flags=re.IGNORECASE)

    # Convert ALTER TABLE ... ADD DEFAULT ... FOR ... to ALTER COLUMN ... SET DEFAULT ...
    # Pattern: ALTER TABLE tbl ADD [CONSTRAINT name] DEFAULT val FOR col
    # We ignore the constraint name since PG manages default constraints differently (usually)
    # or we can keep it? PG: ALTER TABLE tbl ALTER COLUMN col SET DEFAULT val
    # We'll just drop the constraint name part.
    
    # Handle with constraint name: ADD CONSTRAINT name DEFAULT val FOR col
    content = re.sub(r'ALTER\s+TABLE\s+(.*?)\s+ADD\s+CONSTRAINT\s+.*?\s+DEFAULT\s+(.*?)\s+FOR\s+(.*?)(;|$)', 
                     r'ALTER TABLE \1 ALTER COLUMN \3 SET DEFAULT \2\4', content, flags=re.IGNORECASE | re.MULTILINE)
                     
    # Handle without constraint name: ADD DEFAULT val FOR col
    content = re.sub(r'ALTER\s+TABLE\s+(.*?)\s+ADD\s+DEFAULT\s+(.*?)\s+FOR\s+(.*?)(;|$)', 
                     r'ALTER TABLE \1 ALTER COLUMN \3 SET DEFAULT \2\4', content, flags=re.IGNORECASE | re.MULTILINE)

    # Clean up double parens in defaults ((0)) -> 0
    # This is safe to run globally? Maybe. Someties ((a+b)) is valid.
    # But ((0)) is common MSSQL artifact.
    # Let's match SET DEFAULT ((...))
    content = re.sub(r'SET\s+DEFAULT\s+\(\((.*?)\)\)', r'SET DEFAULT \1', content, flags=re.IGNORECASE)

    # Convert INSERT to INSERT INTO
    # Matches INSERT public."Table"
    content = re.sub(r'INSERT\s+public\.', 'INSERT INTO public.', content, flags=re.IGNORECASE)
    
    # Remove N prefix from string literals (e.g. N'Text')
    # Use careful lookbehind to ensure we are matching the start of a string literal
    content = re.sub(r"(?<=[\s,=(])N'", "'", content)

    # Remove CONVERT(Type, (Value)) wrapper often found in defaults
    # E.g. (CONVERT([smallint],(0))) -> (0)
    # We replaced [bit]/[smallint] with SMALLINT/INTEGER already.
    # Regex handles CONVERT(Type, (Val)) -> (Val)
    # Be careful with nested parens.
    # Pattern: CONVERT ( Type , ( Val ) )
    # Let's match specific common cases for 0/1 to be safe
    content = re.sub(r'CONVERT\s*\(\s*SMALLINT\s*,\s*\(\s*([0-9]+)\s*\)\s*\)', r'\1', content, flags=re.IGNORECASE)
    content = re.sub(r'CONVERT\s*\(\s*INTEGER\s*,\s*\(\s*([0-9]+)\s*\)\s*\)', r'\1', content, flags=re.IGNORECASE)
    content = re.sub(r'CONVERT\s*\(\s*BIGINT\s*,\s*\(\s*([0-9]+)\s*\)\s*\)', r'\1', content, flags=re.IGNORECASE)
    
    # Generic cleanup for double parens ((0)) -> (0) only in specific contexts or safer way
    # Global replace of )) is dangerous for CAST(.. AS Decimal(18,2)) -> Decimal(18,2)) which becomes Decimal(18,2)
    # So we use regex to target ((...)) pattern specifically if it looks like a wrapped simple value
    content = re.sub(r'\(\(([0-9]+)\)\)', r'(\1)', content)
    content = re.sub(r'\(\(0\)\)', '(0)', content)
    content = re.sub(r'\(\(1\)\)', '(1)', content)

    # Handle binary literals 0x... -> '\x...'
    # Split by single quote to handle string literals safely
    # This ensures we don't assume 0x inside a string is a binary literal
    parts = content.split("'")
    for i in range(0, len(parts), 2):
        # Process parts outside of strings (even indices)
        # Match 0xXXXX preceded by space, comma, paren, or equals
        # Replace with '\xXXXX' (quoted string)
        # Note: \\x escape for python string and regex replacement
        parts[i] = re.sub(r'(?<=[\s,=(])0x([0-9A-Fa-f]+)', r"'\\x\1'", parts[i])
    content = "'".join(parts)
    
    # Remove ASC/DESC from constraint definitions (e.g. PRIMARY KEY ("Id" ASC))
    # This is a bit aggressive but 'ASC'/'DESC' are keywords usually only for indexes/ordering
    # In table definitions they appear in constraints.
    # We match ASC/DESC followed by comma or closing paren
    content = re.sub(r'\s+(ASC|DESC)\s*(?=[,)])', '', content, flags=re.IGNORECASE)
    # Also handle if it's at end of line
    content = re.sub(r'\s+(ASC|DESC)\s*$', '', content, flags=re.MULTILINE | re.IGNORECASE)
    
    # 7. Remove SQL Server specific table options
    # Important: Remove TEXTIMAGE_ON first to avoid partial matching with ON "PRIMARY"
    content = re.sub(r'\s*TEXTIMAGE_ON\s+"PRIMARY"', '', content, flags=re.IGNORECASE)
    content = re.sub(r'\s*ON\s+"PRIMARY"', '', content, flags=re.IGNORECASE)
    
    # Handle WITH (...) options at table level
    # This might match the closing parenthesis of the table and the WITH block
    content = re.sub(r'\)\s*WITH\s*\([^\)]+\)', ')', content, flags=re.IGNORECASE)

    # 8. Clean up GO and formatting
    lines = content.splitlines()
    new_lines = []
    
    # Header
    new_lines.append("-- Auto-generated PostgreSQL migration script")
    new_lines.append("-- Converted from SQL Server")
    new_lines.append("")
    # Database and User Setup
    new_lines.append("-- Setup Database and User")
    new_lines.append("DO $$")
    new_lines.append("BEGIN")
    new_lines.append("    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'postgres') THEN")
    new_lines.append("        CREATE ROLE postgres WITH LOGIN PASSWORD 'postgres_erp' SUPERUSER;")
    new_lines.append("    ELSE")
    new_lines.append("        ALTER ROLE postgres WITH PASSWORD 'postgres_erp';")
    new_lines.append("    END IF;")
    new_lines.append("END")
    new_lines.append("$$;")
    new_lines.append("")
    
    new_lines.append("-- Note: Run this script with a user that has permission to create databases/roles if these lines are uncommented")
    new_lines.append("-- CREATE DATABASE \"ERP_AI\";") 
    new_lines.append("-- \\c \"ERP_AI\";")
    new_lines.append("")
    
    for line in lines:
        sline = line.strip()
        if sline.upper() == 'GO':
            new_lines.append(';') 
            continue
        if sline == '':
            continue
        if sline == ';': # Avoid empty lines with just semicolon from previous GO replacement cleanup if any
            continue
        new_lines.append(line)

    output = '\n'.join(new_lines)
    
    # Cleanup empty statements
    output = output.replace(';\n;', ';\n')
    
    
    # Handle the table closing ) issue
    # We rely on GO -> ; replacement to handle the main table closing.
    # The previous heuristic caused invalid semicolons inside PRIMARY KEY constraints.
    
    # Clean up double semicolons again
    output = output.replace(';;', ';')
    
    print(f"Writing to {output_file}...")
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(output)
    print("Done.")

if __name__ == "__main__":
    convert_sql(r'D:\AI\AI_Export_insights\data\ERP.sql', r'D:\AI\AI_Export_insights\data\ERP_PostgreSQL.sql')
